### ISSUE TITLE
Local Directory Triggers a Crash

### ISSUE THREAD

**Issue by irresistibl** [ammargitham/WallFlow#88]
Whenever attempting to launch the local directory, the app crashes.

The LogCat for when attempting to launch the local directory for finding local files:

```
FATAL EXCEPTION: main
Process: com.ammar.wallflow.plus, PID: 4700
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2174)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
	at android.app.Activity.startActivityForResult(Activity.java:5596)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(Unknown Source:0)
	at androidx.activity.ComponentActivity$1.onLaunch(SourceFile:269)
	at androidx.activity.result.ActivityResultRegistry$3.launch(SourceFile:26)
	at androidx.activity.compose.ActivityResultLauncherHolder.launch(SourceFile:5)
	at androidx.activity.compose.ManagedActivityResultLauncher.launch(SourceFile:3)
	at com.ammar.wallflow.ui.screens.settings.SettingsScreenKt$SettingsScreen$39.invoke(SourceFile:5)
	at com.ammar.wallflow.ui.screens.settings.SettingsScreenKt$SettingsScreen$39.invoke(SourceFile:1)
	at androidx.collection.ScatterSet$toString$1.invoke(SourceFile:90)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(SourceFile:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlin.TuplesKt.resume(SourceFile:79)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:30)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(SourceFile:118)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:152)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:131)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:131)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:30)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:122)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:214)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1116)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1971)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4388)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:1074)
	at android.view.View.dispatchPointerEvent(View.java:15803)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8153)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10926)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:285)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@1383ec, androidx.compose.runtime.BroadcastFrameClock@f0943b5, StandaloneCoroutine{Cancelling}@c912a4a, AndroidUiDispatcher@3edbdbb]
```

**Comment by irresistibl** [comment]
> You wrote that you are using:
> Brand: samsung, Model: SM-N986B
> Board: exynos990, Manufacturer: samsung
> OS: 13
> 
> Are you using any custom rom?

No, just the Samsung ROM that's been rooted

**Comment by ammargitham** [comment]
From the crash log, it seems you have disable the Files app which is required to choose directories for the 'Local' feature.

**Comment by irresistibl** [comment]
> From the crash log, it seems you have disabled the Files app which is required to choose directories for the 'Local' feature.

That fixed it. Many thanks 😊

**Comment by ammargitham** [comment]
Great. Closing this issue.
