### ISSUE TITLE
Wallflow keeps crashing

### ISSUE THREAD

**Issue by JohnnyBrav0Sr** [ammargitham/WallFlow#92]
Hi

I've been using Wallflow for several months now, and I really LOVE your app! Unfortunately, as of today, the app keeps crashing the moment I try to start it. I run GrapheneOS on a Pixel 6a. Below I attached the crash report:

[wallflow.txt](https://github.com/user-attachments/files/16061630/wallflow.txt)

**Comment by ammargitham** [comment]
This is happening because wallhaven.cc is down.

![image](https://github.com/ammargitham/WallFlow/assets/8017365/cb86b5da-35bd-4980-aa27-8e22178bde71)

**Comment by ammargitham** [comment]
Although, I should add some checks to prevent the crash.

**Comment by ngocanhtve** [comment]
It crash on my phone too:

APP_VERSION_CODE = 2204
APP_VERSION_NAME = 2.6.0-alpha01
PACKAGE_NAME = com.ammar.wallflow
PHONE_MODEL = Xperia 1
ANDROID_VERSION = 14
BRAND = Sony
PRODUCT = J9110

Stacktrace: 
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected start of the object '{', but had '<' instead at path: $
JSON input: <!DOCTYPE html>
<html lang="e.....
	at kotlinx.serialization.json.internal.WriteModeKt.JsonDecodingException(SourceFile:3)
	at kotlinx.serialization.json.internal.WriteModeKt.JsonDecodingException(SourceFile:4)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(SourceFile:59)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(SourceFile:13)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(SourceFile:73)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(SourceFile:48)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(SourceFile:7)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(SourceFile:66)
	at com.ammar.wallflow.data.network.model.wallhaven.NetworkWallhavenWallpapersResponse$$serializer.deserialize(SourceFile:8)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:107)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:31)
	at org.jsoup.parser.Parser.convert(SourceFile:34)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:56)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:9)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [DeferredCoroutine{Cancelling}@4983355, Dispatchers.Main.immediate]

**Comment by ammargitham** [comment]
@ngocanhtve As mentioned it is happening because the site is down. Keep an eye on https://wallhaven.cc/ to check current status.
